### PR TITLE
ci(pr-build): ONLY keep arm64, amd64 as build targets

### PR DESCRIPTION
**Pull request by yqlbu**
### Background

As the title suggests. The idea is to drastically reduce build time.

### Checklist

- [x] The Pull Request has been fully tested
- [ ] There's an entry in the CHANGELOGS
- [ ] There is a user-facing docs PR against https://github.com/daeuniverse/dae

### Full changelogs

- ci(pr-build): ONLY keep arm64, amd64 as build targets
- patch(friendly-filenames.json): add entry for amd64 

### Issue reference

NA

### Test Result

image

image

### CODE REVIEW

**Review by mzz2017 — APPROVED** [review]

**Review by mzz2017 — APPROVED** [review]

**Review by mzz2017 — CHANGES_REQUESTED** [review]
I think we should retain arm 5 6 7.

**Comment by yqlbu** [comment]
> I think we should retain arm 5 6 7.

Why's that?

**Comment by mzz2017** [comment]
> Why's that?

Many users use them. And they are not slow in building.

**Comment by yqlbu** [comment]
> > Why's that?
> 
> Many users use them. And they are not slow in building.

Sure, I will add them back.

**Review by kunish — CHANGES_REQUESTED** [review]
Please double check

**Review by mzz2017 — APPROVED** [review]
LGTM.

**Review by kunish — APPROVED** [review]

**Pull request merged**
