### PR TITLE
ci: build-nightly workflow

### PR DESCRIPTION
**Pull request by yqlbu**
### Background

Add nightly build to test cutting-edge/tentative features.

The `nightly(develop)` branch will be paralleled to the `main(default)` branch as they server for different purposes.

Basically, develop branch has more freedom when it comes to testing stability for any new feature implementation. Whereas, the mainstream should be considered as a `stable` branch where we ONLY merge fully tested and stable commits.

### Checklist

- [x] The Pull Request has been fully tested
- [ ] There's an entry in the CHANGELOG
- [ ] There is a user-facing docs PR against https://github.com/daeuniverse/daed

### Full changelog

- ci: build-nightly workflow

### Issue reference

NA

### CODE REVIEW

**Comment by kunish** [comment]
It seems now there is no Github prerelease will be published anymore.

What do we do to the existing prerelease?

https://github.com/daeuniverse/daed/releases/tag/Prerelease

**Comment by yqlbu** [comment]
> It seems now there is no Github prerelease will be published anymore.
> 
> What do we do to the existing prerelease?
> 
> https://github.com/daeuniverse/daed/releases/tag/Prerelease

Let’s leave it there as it is.

**Comment by kunish** [comment]
> > It seems now there is no Github prerelease will be published anymore.
> > What do we do to the existing prerelease?
> > https://github.com/daeuniverse/daed/releases/tag/Prerelease
> 
> The release will still function please check build.yml. When it comes to the exiting preleaase, let’s leave it there as it is.

It wont function anymore because the develop branch is being removed from the on push branches list

https://github.com/daeuniverse/daed/pull/35/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R290-R323

**Comment by kunish** [comment]
So either we comment it out or we remove it completely

**Review by kunish — DISMISSED** [review]

**Review by kunish — APPROVED** [review]

**Pull request merged**
