### PR TITLE
fix bunch of issues, add bunch of missing functionalities, collected from our community

### PR DESCRIPTION
**Pull request by kunish**
### Checklist

- [ ] The Pull Request has been fully tested
- [x] There's an entry in the CHANGELOG
- [ ] There is a user-facing docs PR against https://github.com/daeuniverse/daed

### Full changelog

- feat: use source code pro font for dns/routing input
- feat: set cursor type of input as pointer
- feat: add support for subscription nodes drag and drop to groups
- feat: update group policy and group name
- feat(group): hide nodes and subscriptions if empty
- feat: display rule details with modal
- feat(subscription): collapsible node list
- feat(rfc): show reload when specific mutations happen
- fix: drop simple mode for now as its feature set is not quite there yet
- fix: swap node name and tag display, tags are required
- fix: remove extra dns and routing spaces
- fix: default routing referencing old group name (default)
- fix: parse duration correctly to avoid time unit response inconsistency with request
- fix: config form may lack behind from the user inputs
- ci: fix mips build issue
- chore: upgrade dae-wing

### Issue reference

Fixes https://github.com/daeuniverse/daed/issues/56

### CODE REVIEW

**Comment by mzz2017** [comment]
@kunish Could you please explain it in more detail?

**Comment by kunish** [comment]
> @kunish Could you please explain it in more detail?

Yes. I will add those in the `Full Changelog` later. This was supposed to be a WIP PR tho.

**Comment by mzz2017** [comment]
@kunish Thanks bro.

**Comment by kunish** [comment]
@yqlbu We need to fix CI issues first

**Comment by yqlbu** [comment]
> @yqlbu We need to fix CI issues first

Sync issue you mean?

**Comment by mzz2017** [comment]
The pointers are different. See the two images:
image
image

**Comment by mzz2017** [comment]
New UI is not competible with old one. You can see that I have a `default` group instead.
I think it is acceptable in `test` period. However, we should pay more attention to those `breaking` change in the future stable versions.
image

**Comment by kunish** [comment]
> The pointers are different. See the two images: image image

Fixed with 07a3637c8990dd8f329f05d91830c859740c9763

**Comment by mzz2017** [comment]
> fix: swap node name and tag display, tags are required
Nothing is `required` in dae-wing. It is a limit of the frontend. Tag is just a `alias` and is different from this terminology in dae. We do not need to `swap`; we can use alias first and fallback to node name.

**Comment by kunish** [comment]
> The new UI is not compatible with the old one. You can see that I have a `default` group instead, but errors occurred. I have to remove my database and go back to the start. I think it is acceptable in the `test` period. However, we should pay more attention to those `breaking` changes in the future stable versions. image

Yes. This part 

> The new UI is not compatible with the old one. You can see that I have a `default` group instead, but errors occurred. I have to remove my database and go back to the start. I think it is acceptable in the `test` period. However, we should pay more attention to those `breaking` changes in the future stable versions. image

Yes. We definitely should pay more attention about this. These breaking changes are gonna be unacceptable in the future

**Comment by kunish** [comment]
/cc @mzz2017 

https://github.com/daeuniverse/dae-wing/pull/34

> > fix: swap node name and tag display, tags are required.
> 
> Nothing is `required` in dae-wing. It does be a limit of the frontend. Tag is just an `alias` and is different from this terminology in dae. We do not need to `swap`; we can use the alias first and fallback to the node name.

UI can benefit from this I guess? If a user just copy and paste the link from their provider, they can decide what the name would be given them more control

**Comment by mzz2017** [comment]
> UI can benefit from this I guess? If a user just copy and paste the link from their provider, they can decide what the name would be given them more control

Good point. Maybe they can also `add` an alias later if they want?

**Comment by kunish** [comment]
> > UI can benefit from this I guess? If a user just copy and paste the link from their provider, they can decide what the name would be given them more control
> 
> Good point. Maybe they can also `add` an alias later if they want?

Correct.

**Comment by yqlbu** [comment]
Please ignore the message above (the one sent by bot).

**Review by yqlbu — DISMISSED** [review]

**Comment by mzz2017** [comment]
我打个包给首席测试一下

**Comment by kunish** [comment]
@mzz2017 ok, you do that

**Comment by yqlbu** [comment]
I've deployed `branch-up-to-date` bot; so your pr will be automatically synced to `origin/main` if and ONLY if new commits are pushed to `origin/main` before you merge this PR.

**Comment by mzz2017** [comment]
Our Chief Test Officer says everything looks nice.

However, I found that adding nodes/subscriptions to a group would not trigger showing the reload button. I guess removing either.

**Comment by kunish** [comment]
> Our Chief Test Officer says everything looks nice.
> 
> However, I found that adding nodes/subscriptions to a group would not trigger showing the reload button. I guess so does removing.

That's expected behavior. I did not know if adding or removing nodes/subscriptions from a group should trigger modified changes happen. I'll add those if you say so.

**Pull request merged**
